export default {
    ANSWER_QUESTION: 'ANSWER_QUESTION',
    ASK_QUESTION: 'ASK_QUESTION',
    CREATE_GAME: 'CREATE_GAME',
    GAME_CREATED: 'GAME_CREATED',
    GAME_STARTED: 'GAME_STARTED',
    GAME_STATE_ACKNOWLEDGED: 'GAME_STATE_ACKNOWLEDGED',
    GUESS_VALIDATED: 'GUESS_VALIDATED',
    JOIN_GAME: 'JOIN_GAME',
    PLAYER_JOINED: 'PLAYER_JOINED',
    PLAYER_LEFT: 'PLAYER_LEFT',
    QUESTION_ANSWERED: 'QUESTION_ANSWERED',
    QUESTION_ASKED: 'QUESTION_ASKED',
    REQUEST_GAME_STATE: 'REQUEST_GAME_STATE',
    START_GAME: 'START_GAME',
    SUBMIT_GUESS: 'SUBMIT_GUESS'
};