export default {
    CREATE_GAME: 'CREATE_GAME',
    GAME_CREATED: 'GAME_CREATED',
    GAME_STARTED: 'GAME_STARTED',
    GAME_STATE_ACKNOWLEDGED: 'GAME_STATE_ACKNOWLEDGED',
    JOIN_GAME: 'JOIN_GAME',
    PLAYER_JOINED: 'PLAYER_JOINED',
    PLAYER_LEFT: 'PLAYER_LEFT',
    REQUEST_GAME_STATE: 'REQUEST_GAME_STATE',
    START_GAME: 'START_GAME'
};